exclude:
  - '/img/biloma/*.txt'
  - '/node_modules/'
  - '/.eslintrc.json'
  - '/CNAME'
  - '/Gemfile'
  - '/Gemfile.lock'
  - '/package-lock.json'
  - '/package.json'
  - '/tex2svg.js'

defaults:
  - scope:
      path: ''
    values:
      article: true
      styles: []
      scripts: []

kramdown:
  auto_ids: false